radius:
  container_name: radius
  restart: always
  image: radius
  volumes:
    - /var/log/radius:/var/log/radius
  tty: true
  ports:
    - "1812/tcp:1812/tcp"
    - "1813/tcp:1813/tcp"
    - "1812/udp:1812/udp"
    - "1813/udp:1813/udp"
